### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by cxde-Sujal** [anjalit03/Dazzle-and-Delight#22] opened 2024-10-27 21:11 UTC
![Screenshot (236)](https://github.com/user-attachments/assets/beca0be9-04a8-4960-af42-98566f38fc76)
Addition of footer with social media links .
@anjalit03 assign it to me for Hacktober please

**Comment by anjalit03** [comment] 2024-10-28 15:24
the issue is already raised and assigned to someone else

**Closed** 2024-10-28 15:25 UTC
Labels: duplicate
